### ISSUE TITLE
Command failed: File to read not found or unreadable: /Users/USERNAME/Library/Mobile

### ISSUE THREAD

**Issue by OKNoah** [Arcath/sass-watch#1]
I get this error when I try save a watched file.

`Command failed: /bin/sh -c /Users/USERNAME/.atom/packages/sass-watch/node_modules/.bin/node-sass /Users/noah/Library/Mobile Documents/com~apple~CloudDocs/PATH/TO/style.scss /Users/USERNAME/Library/Mobile Documents/com~apple~CloudDocs/PATH/TO/style.css Error: File to read not found or unreadable: /Users/USERNAME/Library/Mobile`

**Comment by Arcath** [comment]
It was stopping at the first space which is why it was reporting that `/Users/USERNAME/Library/Mobile` could not be found or was unreadable.

I've updated Sass-Watch to put quote the file paths when running the command seemed to fix the issue when I replicated it. Let me know if your still having problems
